### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by oterox** [Tony133/Symfony4APIBoilerplateJWT#4]
Hi, 
I'm using postman to check the API and i can't get the token.
I can register a user but when i try to get the token i get a 404:
"No route found for \"POST /api/token/"
The same happens with your other repository with books.

The response:
{"error":{"code":404,"message":"Not Found","exception":[{"message":"Not Found","class":"Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/home\/oterox\/sites\/Symfony4APIBoilerplateJWT\/vendor\/symfony\/framework-bundle\/Controller\/ControllerTrait.php","line":286,"args":[]},{"namespace":"Symfony\\Bundle\\FrameworkBundle\\Controller","short_class":"Controller","class":"Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller","type":"->","function":"createNotFoundException","file":"\/home\/oterox\/sites\/Symfony4APIBoilerplateJWT\/src\/Controller\/LoginController.php","line":25,"args":[]},{"namespace":"App\\Controller","short_class":"LoginController","class":"App\\Controller\\LoginController","type":"->","function":"newTokenAction","file":"\/home\/oterox\/sites\/Symfony4APIBoilerplateJWT\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":150,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handleRaw","file":"\/home\/oterox\/sites\/Symfony4APIBoilerplateJWT\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":67,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handle","file":"\/home\/oterox\/sites\/Symfony4APIBoilerplateJWT\/vendor\/symfony\/http-kernel\/Kernel.php","line":198,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->","function":"handle","file":"\/home\/oterox\/sites\/Symfony4APIBoilerplateJWT\/public\/index.php","line":28,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]}]}]}}

Any idea why?

Thk.

**Comment by Tony133** [comment]
Hello,

I personally tried it now but it does login to me (see screeshot), I used the user I tested as doctrine fixtures.

This is the curl command I made:
curl -H 'content-type: application/json' -v -X  POST http://127.0.0.1:8000/api/token -H 'Authorization:Basic dG9ueV9hZG1pbjphZG1pbg=='

Remember that username and password must be encoded in base64, I do not write it in the README as it should not be difficult to remember, then if it is necessary I rewrite it.

Try the procedure again you put the password that is in the .env file that is used during the generation of the ssh key.

<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/55294092-0c9e2480-53fe-11e9-8385-6c8a8dcf1372.png">

I hope I was helpful

Tony133
